### ISSUE TITLE
[PE-D][Tester A] When launching the app for the first time, the GUI does not match the description in the UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T13-1/tp#161]
UG：
![image.png](https://raw.githubusercontent.com/NusMinato/ped/main/files/cef4aba0-c47e-4242-990c-87e3287300ee.png)
APP：
![image.png](https://raw.githubusercontent.com/NusMinato/ped/main/files/12c94275-c5fb-4d78-9da8-5b3e208fa306.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: NusMinato/ped#1

**Comment by taniatsq** [comment]
updated ug
