### ISSUE TITLE
[PE-D][Tester B] Inconsistent commands in UG and app (add, edit)

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T13-1/tp#184]
The ability to add attendance through ar/ and description through desc/ is not mentioned in the UG.

From app it is 

Parameters: INDEX (must be a positive integer) [n/NAME] [p/PHONE] [e/EMAIL] [s/STUDENTID] [ar/Attendance][desc/DESCRIPTION]...
 Example: edit 1 p/91234567 e/johndoe@example.com

![Screenshot 2024-04-05 at 17.01.47.png](https://raw.githubusercontent.com/ThatGirlJam/ped/main/files/0738795a-6315-45b6-8fd9-56a8937f2c66.png)

May need to edit this in summary too

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: ThatGirlJam/ped#24

**Comment by nichee** [comment]
Edited
