### ISSUE TITLE
[PE-D][Tester A] App disallows use of s/o even though it may be part of a person's legal name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T13-1/tp#188]
![image.png](https://raw.githubusercontent.com/NusMinato/ped/main/files/5fd1a657-5ff3-45d7-9ab4-7af4242e1a19.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: NusMinato/ped#3

**Comment by taniatsq** [comment]
update in ug (say which command cannot have what, / will apply to all)
use this as example

**Comment by taniatsq** [comment]
updated ug to say that name and description only takes in alphanumeric characters and whitespace
